=== fragwuerdig/skip-go-registry/initia.chain.schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "title": "Chain",
    "type": "object",
    "required": [
        "chain_id",
        "is_testnet",
        "chain_name",
        "chain_type"
    ],
    "properties": {
        "$schema": {
            "type": "string",
            "minLength": 1,
            "pattern": "^(\\.\\./)+initia.chain\\.schema\\.json$"
        },
        "chain_id": {
            "type": "string",
            "minLength": 1,
            "pattern": "[a-z0-9-]+",
            "examples": [
                "initiation-1"
            ]
        },
        "is_testnet": {
            "type": "boolean",
            "default": false
        },
        "chain_name": {
            "type": "string",
            "minLength": 1,
            "pattern": "[a-z0-9]+",
            "examples": [
                "minimove"
            ]
        },
        "is_initia_l1": {
            "type": "boolean",
            "default": false
        },
        "initia_l1_chain_id": {
            "type": "string",
            "minLength": 1,
            "pattern": "[a-z0-9-]+",
            "description": "The chain ID of the L1 chain. Required if the chain is an L2.",
            "examples": [
                "initiation-1"
            ]
        },
        "chain_type": {
            "const": "initia"
        },
        "apis": {
            "type": "object",
            "properties": {
                "required": [
                    "cosmos_sdk_grpc_endpoint",
                    "tendermint_rpc_endpoint"
                ],
                "lcd_rest_endpoint": {
                    "$ref": "#/$defs/endpoint",
                    "description": "Only required for initia-1."
                },
                "tendermint_rpc_endpoint": {
                    "$ref": "#/$defs/endpoint"
                },
                "cosmos_sdk_grpc_endpoint": {
                    "$ref": "#/$defs/grpc_endpoint"
                }
            },
            "additionalProperties": false
        }
    },
    "anyOf": [
        {
            "properties": {
                "is_initia_l1": { "const": true }
            }
        },
        {
            "properties": {
                "is_initia_l1": { "const": false }
            },
            "required": ["initia_l1_chain_id"]
        }
    ],
    "$defs": {
        "endpoint": {
            "type": "object",
            "required": [
                "address"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "format": "uri"
                },
                "provider": {
                    "type": "string"
                },
                "archive": {
                    "type": "boolean",
                    "default": false
                },
                "backoff_delay": {
                    "type": "integer",
                    "description": "Delay in milliseconds between request retires."
                },
                "basic_auth_required": {
                    "type": "boolean",
                    "default": false,
                    "description": "If basic HTTP authentication (username + password) is required to access this endpoint."
                },
                "index_for_skip": {
                    "type": "number",
                    "description": "The index for the basic auth salt generation."
                }
            }
        },
        "grpc_endpoint": {
            "allOf": [
                {
                    "$ref": "#/$defs/endpoint"
                },
                {
                    "type": "object",
                    "properties": {
                        "tls": {
                            "type": "boolean",
                            "description": "If TLS is required to access this GRPC endpoint.",
                            "default": false
                        }
                    }
                }
            ]
        }
    }
}

=== fragwuerdig/skip-go-registry/chains/bfb-1/chain.json
{
  "$schema": "../../initia.chain.schema.json",
  "chain_id": "bfb-1",
  "is_testnet": false,
  "chain_name": "bfb",
  "chain_type": "initia",
  "is_initia_l1": false,
  "initia_l1_chain_id": "interwoven-1",
  "apis": {
    "tendermint_rpc_endpoint": {
      "address": "https://rpc-bfb-1.anvil.asia-southeast.initia.xyz",
      "backoff_delay": 1000
    },
    "lcd_rest_endpoint": {
      "address": "https://rest-bfb-1.anvil.asia-southeast.initia.xyz",
      "backoff_delay": 1000
    },
    "cosmos_sdk_grpc_endpoint": {
      "address": "grpc-bfb-1.anvil.asia-southeast.initia.xyz:443",
      "backoff_delay": 0,
      "tls": true
    }
  }
}

=== fragwuerdig/skip-go-registry/chains/init-ai-1/chain.json
{
    "$schema": "../../initia.chain.schema.json",
    "chain_id": "init-ai-1",
    "is_testnet": true,
    "chain_name": "init_ai",
    "chain_type": "initia",
    "apis": {
        "tendermint_rpc_endpoint": {
            "address": "https://maze-rpc-617bacff-7d34-4eb8-87f4-ee16fb4e0ac7.ue1-prod.newmetric.xyz",
            "backoff_delay": 1000
        },
        "lcd_rest_endpoint": {
            "address": "https://maze-rest-617bacff-7d34-4eb8-87f4-ee16fb4e0ac7.ue1-prod.newmetric.xyz",
            "backoff_delay": 1000
        },
        "cosmos_sdk_grpc_endpoint": {
            "address": "54.147.50.234:31001",
            "backoff_delay": 0,
            "tls": true
        }
    }
}

=== fragwuerdig/skip-go-registry/chains/rehearsal-1/chain.json
{
  "$schema": "../../initia.chain.schema.json",
  "chain_id": "rehearsal-1",
  "is_testnet": true,
  "chain_name": "initia",
  "chain_type": "initia",
  "apis": {
    "tendermint_rpc_endpoint": {
      "address": "https://rpc-skip.rehearsal-1.initia.xyz",
      "provider": "Initia Labs",
      "backoff_delay": 1000,
      "basic_auth_required": true
    },
    "lcd_rest_endpoint": {
      "address": "https://rest-skip.rehearsal-1.initia.xyz",
      "provider": "Initia Labs",
      "backoff_delay": 1000,
      "basic_auth_required": true
    },
    "cosmos_sdk_grpc_endpoint": {
      "address": "grpc-skip.rehearsal-1.initia.xyz:443",
      "provider": "Initia Labs",
      "backoff_delay": 0,
      "tls": true,
      "basic_auth_required": true
    }
  }
}

=== fragwuerdig/skip-go-registry/chains/preyominet-1/chain.json
{
    "$schema": "../../initia.chain.schema.json",
    "chain_id": "preyominet-1",
    "is_testnet": true,
    "chain_name": "yominet",
    "chain_type": "initia",
    "apis": {
        "tendermint_rpc_endpoint": {
            "address": "https://rpc.preyominet.initia.tech",
            "backoff_delay": 1000
        },
        "lcd_rest_endpoint": {
            "address": "https://lcd.preyominet-1.initia.tech",
            "backoff_delay": 1000
        },
        "cosmos_sdk_grpc_endpoint": {
            "address": "maze-grpc-s2-9ce4b2ff-e329-459d-8baa-ae49f95f33b2.public-think-factory.newmetric.xyz:443 ",
            "backoff_delay": 0,
            "tls": true
        }
    }
}

=== fragwuerdig/skip-go-registry/chains/rehearsal-miniwasm-1/chain.json
{
  "$schema": "../../initia.chain.schema.json",
  "chain_id": "rehearsal-miniwasm-1",
  "is_testnet": true,
  "chain_name": "miniwasm",
  "chain_type": "initia",
  "apis": {
    "tendermint_rpc_endpoint": {
      "address": "https://rpc-rehearsal-miniwasm-1.anvil.asia-southeast.staging.initia.xyz",
      "provider": "Initia Labs",
      "backoff_delay": 1000
    },
    "lcd_rest_endpoint": {
      "address": "https://rest-rehearsal-miniwasm-1.anvil.asia-southeast.staging.initia.xyz",
      "provider": "Initia Labs",
      "backoff_delay": 1000
    },
    "cosmos_sdk_grpc_endpoint": {
      "address": "grpc-rehearsal-miniwasm-1.anvil.asia-southeast.staging.initia.xyz:443",
      "provider": "Initia Labs",
      "backoff_delay": 0,
      "tls": true
    }
  }
}

=== fragwuerdig/skip-go-registry/chains/miniwasm-1/chain.json
{
    "$schema": "../../initia.chain.schema.json",
    "chain_id": "miniwasm-1",
    "is_testnet": true,
    "chain_name": "miniwasm",
    "chain_type": "initia",
    "apis": {
        "tendermint_rpc_endpoint": {
            "address": "https://rpc-skip.miniwasm-1.initia.xyz",
            "provider": "Initia Labs",
            "backoff_delay": 1000,
            "basic_auth_required": true
        },
        "lcd_rest_endpoint": {
            "address": "https://lcd-skip.miniwasm-1.initia.xyz",
            "provider": "Initia Labs",
            "backoff_delay": 1000
        },
        "cosmos_sdk_grpc_endpoint": {
            "address": "34.124.147.66:9090",
            "provider": "Initia Labs",
            "backoff_delay": 0,
            "tls": false,
            "basic_auth_required": true
        }
    }
}

=== fragwuerdig/skip-go-registry/chains/interwoven-1/chain.json
{
  "$schema": "../../initia.chain.schema.json",
  "chain_id": "interwoven-1",
  "is_testnet": false,
  "chain_name": "initia",
  "chain_type": "initia",
  "is_initia_l1": true,
  "apis": {
      "tendermint_rpc_endpoint": {
          "address": "https://rpc-skip.initia.xyz",
          "provider": "Initia Labs",
          "backoff_delay": 1000,
          "basic_auth_required": true
      },
      "lcd_rest_endpoint": {
          "address": "https://rest-skip.initia.xyz",
          "provider": "Initia Labs",
          "backoff_delay": 1000,
          "basic_auth_required": true
      },
      "cosmos_sdk_grpc_endpoint": {
          "address": "grpc-skip.initia.xyz:443",
          "provider": "Initia Labs",
          "backoff_delay": 0,
          "tls": true,
          "basic_auth_required": true
      }
  }
}

=== fragwuerdig/skip-go-registry/chains/culinaris-2/chain.json
{
  "$schema": "../../initia.chain.schema.json",
  "chain_id": "culinaris-2",
  "is_testnet": true,
  "chain_name": "culinaris",
  "chain_type": "initia",
  "is_initia_l1": false,
  "initia_l1_chain_id": "initiation-2",
  "apis": {
    "tendermint_rpc_endpoint": {
      "address": "https://rpc.culinaris-2.initia.tech",
      "backoff_delay": 1000
    },
    "lcd_rest_endpoint": {
      "address": "https://rest.culinaris-2.initia.tech",
      "backoff_delay": 1000
    },
    "cosmos_sdk_grpc_endpoint": {
      "address": "grpc.culinaris-2.initia.tech:443",
      "backoff_delay": 0,
      "tls": true
    }
  }
}
