=== fragwuerdig/skip-go-registry/initia.chain.schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "title": "Chain",
    "type": "object",
    "required": [
        "chain_id",
        "is_testnet",
        "chain_name",
        "chain_type"
    ],
    "properties": {
        "$schema": {
            "type": "string",
            "minLength": 1,
            "pattern": "^(\\.\\./)+initia.chain\\.schema\\.json$"
        },
        "chain_id": {
            "type": "string",
            "minLength": 1,
            "pattern": "[a-z0-9-]+",
            "examples": [
                "initiation-1"
            ]
        },
        "is_testnet": {
            "type": "boolean",
            "default": false
        },
        "chain_name": {
            "type": "string",
            "minLength": 1,
            "pattern": "[a-z0-9]+",
            "examples": [
                "minimove"
            ]
        },
        "is_initia_l1": {
            "type": "boolean",
            "default": false
        },
        "initia_l1_chain_id": {
            "type": "string",
            "minLength": 1,
            "pattern": "[a-z0-9-]+",
            "description": "The chain ID of the L1 chain. Required if the chain is an L2.",
            "examples": [
                "initiation-1"
            ]
        },
        "chain_type": {
            "const": "initia"
        },
        "apis": {
            "type": "object",
            "properties": {
                "required": [
                    "cosmos_sdk_grpc_endpoint",
                    "tendermint_rpc_endpoint"
                ],
                "lcd_rest_endpoint": {
                    "$ref": "#/$defs/endpoint",
                    "description": "Only required for initia-1."
                },
                "tendermint_rpc_endpoint": {
                    "$ref": "#/$defs/endpoint"
                },
                "cosmos_sdk_grpc_endpoint": {
                    "$ref": "#/$defs/grpc_endpoint"
                }
            },
            "additionalProperties": false
        }
    },
    "anyOf": [
        {
            "properties": {
                "is_initia_l1": { "const": true }
            }
        },
        {
            "properties": {
                "is_initia_l1": { "const": false }
            },
            "required": ["initia_l1_chain_id"]
        }
    ],
    "$defs": {
        "endpoint": {
            "type": "object",
            "required": [
                "address"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "format": "uri"
                },
                "provider": {
                    "type": "string"
                },
                "archive": {
                    "type": "boolean",
                    "default": false
                },
                "backoff_delay": {
                    "type": "integer",
                    "description": "Delay in milliseconds between request retires."
                },
                "basic_auth_required": {
                    "type": "boolean",
                    "default": false,
                    "description": "If basic HTTP authentication (username + password) is required to access this endpoint."
                },
                "index_for_skip": {
                    "type": "number",
                    "description": "The index for the basic auth salt generation."
                }
            }
        },
        "grpc_endpoint": {
            "allOf": [
                {
                    "$ref": "#/$defs/endpoint"
                },
                {
                    "type": "object",
                    "properties": {
                        "tls": {
                            "type": "boolean",
                            "description": "If TLS is required to access this GRPC endpoint.",
                            "default": false
                        }
                    }
                }
            ]
        }
    }
}

=== fragwuerdig/skip-go-registry/chains/zaar-testnet-3/chain.json
{
  "$schema": "../../initia.chain.schema.json",
  "chain_id": "zaar-testnet-3",
  "is_testnet": true,
  "chain_name": "zaar",
  "chain_type": "initia",
  "apis": {
    "tendermint_rpc_endpoint": {
      "address": "https://rpc-zaar-testnet-3.anvil.initia.xyz",
      "backoff_delay": 1000
    },
    "lcd_rest_endpoint": {
      "address": "https://rest-zaar-testnet-3.anvil.initia.xyz",
      "backoff_delay": 1000
    },
    "cosmos_sdk_grpc_endpoint": {
      "address": "grpc-zaar-testnet-3.anvil.initia.xyz:443",
      "backoff_delay": 0,
      "tls": true
    }
  }
}

=== fragwuerdig/skip-go-registry/chains/zaar-testnet-5/chain.json
{
  "$schema": "../../initia.chain.schema.json",
  "chain_id": "zaar-testnet-5",
  "is_testnet": true,
  "chain_name": "zaar",
  "chain_type": "initia",
  "is_initia_l1": false,
  "initia_l1_chain_id": "initiation-2",
  "apis": {
    "tendermint_rpc_endpoint": {
      "address": "https://rpc-zaar-testnet-5.anvil.asia-southeast.initia.xyz",
      "backoff_delay": 1000
    },
    "lcd_rest_endpoint": {
      "address": "https://rest-zaar-testnet-5.anvil.asia-southeast.initia.xyz",
      "backoff_delay": 1000
    },
    "cosmos_sdk_grpc_endpoint": {
      "address": "grpc-zaar-testnet-5.anvil.asia-southeast.initia.xyz:443",
      "backoff_delay": 0,
      "tls": true
    }
  }
}

=== fragwuerdig/skip-go-registry/chains/testbfb/chain.json
{
  "$schema": "../../initia.chain.schema.json",
  "chain_id": "testbfb-3",
  "is_testnet": true,
  "chain_name": "testbfb",
  "chain_type": "initia",
  "is_initia_l1": false,
  "initia_l1_chain_id": "initiation-2",
  "apis": {
    "tendermint_rpc_endpoint": {
      "address": "https://rpc-testbfb-3.anvil.europe-west.initia.xyz",
      "backoff_delay": 1000
    },
    "lcd_rest_endpoint": {
      "address": "https://rest-testbfb-3.anvil.europe-west.initia.xyz",
      "backoff_delay": 1000
    },
    "cosmos_sdk_grpc_endpoint": {
      "address": "grpc-testbfb-3.anvil.europe-west.initia.xyz:443",
      "backoff_delay": 0,
      "tls": true
    }
  }
}

=== fragwuerdig/skip-go-registry/chains/intergaze-1/chain.json
{
  "$schema": "../../initia.chain.schema.json",
  "chain_id": "intergaze-1",
  "is_testnet": false,
  "chain_name": "intergaze",
  "chain_type": "initia",
  "is_initia_l1": false,
  "initia_l1_chain_id": "interwoven-1",
  "apis": {
    "tendermint_rpc_endpoint": {
      "address": "https://rpc.intergaze-apis.com/",
      "backoff_delay": 1000
    },
    "lcd_rest_endpoint": {
      "address": "https://rest.intergaze-apis.com/",
      "backoff_delay": 1000
    },
    "cosmos_sdk_grpc_endpoint": {
      "address": "grpc-skip.intergaze-apis.com:443",
      "backoff_delay": 0,
      "tls": true
    }
  }
}

=== fragwuerdig/skip-go-registry/chains/infinityg-1/chain.json
{
  "$schema": "../../initia.chain.schema.json",
  "chain_id": "infinityg-1",
  "is_testnet": true,
  "chain_name": "infinityg",
  "chain_type": "initia",
  "is_initia_l1": false,
  "initia_l1_chain_id": "initiation-2",
  "apis": {
    "tendermint_rpc_endpoint": {
      "address": "https://rpc-infinityg-1.anvil.asia-southeast.initia.xyz",
      "backoff_delay": 1000
    },
    "lcd_rest_endpoint": {
      "address": "https://rest-infinityg-1.anvil.asia-southeast.initia.xyz",
      "backoff_delay": 1000
    },
    "cosmos_sdk_grpc_endpoint": {
      "address": "grpc-infinityg-1.anvil.asia-southeast.initia.xyz:443",
      "backoff_delay": 0,
      "tls": true
    }
  }
}

=== fragwuerdig/skip-go-registry/chains/initiation-2/chain.json
{
    "$schema": "../../initia.chain.schema.json",
    "chain_id": "initiation-2",
    "is_testnet": true,
    "chain_name": "initia",
    "chain_type": "initia",
    "apis": {
        "tendermint_rpc_endpoint": {
            "address": "https://rpc-skip.initiation-2.initia.xyz",
            "provider": "Initia Labs",
            "backoff_delay": 1000,
            "basic_auth_required": true
        },
        "lcd_rest_endpoint": {
            "address": "https://rest-skip.initiation-2.initia.xyz",
            "provider": "Initia Labs",
            "backoff_delay": 1000,
            "basic_auth_required": true
        },
        "cosmos_sdk_grpc_endpoint": {
            "address": "skip-grpc.testnet.initia.xyz:443",
            "provider": "Initia Labs",
            "backoff_delay": 0,
            "tls": true,
            "basic_auth_required": true
        }
    }
}

=== fragwuerdig/skip-go-registry/chains/glados-1/chain.json
{
    "$schema": "../../initia.chain.schema.json",
    "chain_id": "glados-1",
    "is_testnet": true,
    "chain_name": "milkyway",
    "chain_type": "initia",
    "apis": {
        "tendermint_rpc_endpoint": {
            "address": "https://rpc-skip.testnet.milkyway.zone",
            "backoff_delay": 1000,
            "basic_auth_required": true,
            "index_for_skip": 0
        },
        "lcd_rest_endpoint": {
            "address": "https://lcd-skip.testnet.milkyway.zone",
            "backoff_delay": 1000,
            "basic_auth_required": true,
            "index_for_skip": 0
        },
        "cosmos_sdk_grpc_endpoint": {
            "address": "grpc-skip.testnet.milkyway.zone:443",
            "backoff_delay": 0,
            "tls": true,
            "basic_auth_required": true,
            "index_for_skip": 0
        }
    }
}

=== fragwuerdig/skip-go-registry/chains/glados-2.1/chain.json
{
    "$schema": "../../initia.chain.schema.json",
    "chain_id": "glados-2.1",
    "is_testnet": true,
    "chain_name": "milkyway",
    "chain_type": "initia",
    "is_initia_l1": false,
    "initia_l1_chain_id": "initiation-2",
    "apis": {
        "tendermint_rpc_endpoint": {
            "address": "https://rpc-skip.rollup-testnet.milkyway.zone",
            "backoff_delay": 1000,
            "basic_auth_required": true,
            "index_for_skip": 0
        },
        "lcd_rest_endpoint": {
            "address": "https://lcd-skip.rollup-testnet.milkyway.zone",
            "backoff_delay": 1000,
            "basic_auth_required": true,
            "index_for_skip": 0
        },
        "cosmos_sdk_grpc_endpoint": {
            "address": "grpc-skip.rollup-testnet.milkyway.zone:443",
            "backoff_delay": 0,
            "tls": true,
            "basic_auth_required": true,
            "index_for_skip": 0
        }
    }
}
