=== fragwuerdig/skip-go-registry/initia.chain.schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "title": "Chain",
    "type": "object",
    "required": [
        "chain_id",
        "is_testnet",
        "chain_name",
        "chain_type"
    ],
    "properties": {
        "$schema": {
            "type": "string",
            "minLength": 1,
            "pattern": "^(\\.\\./)+initia.chain\\.schema\\.json$"
        },
        "chain_id": {
            "type": "string",
            "minLength": 1,
            "pattern": "[a-z0-9-]+",
            "examples": [
                "initiation-1"
            ]
        },
        "is_testnet": {
            "type": "boolean",
            "default": false
        },
        "chain_name": {
            "type": "string",
            "minLength": 1,
            "pattern": "[a-z0-9]+",
            "examples": [
                "minimove"
            ]
        },
        "is_initia_l1": {
            "type": "boolean",
            "default": false
        },
        "initia_l1_chain_id": {
            "type": "string",
            "minLength": 1,
            "pattern": "[a-z0-9-]+",
            "description": "The chain ID of the L1 chain. Required if the chain is an L2.",
            "examples": [
                "initiation-1"
            ]
        },
        "chain_type": {
            "const": "initia"
        },
        "apis": {
            "type": "object",
            "properties": {
                "required": [
                    "cosmos_sdk_grpc_endpoint",
                    "tendermint_rpc_endpoint"
                ],
                "lcd_rest_endpoint": {
                    "$ref": "#/$defs/endpoint",
                    "description": "Only required for initia-1."
                },
                "tendermint_rpc_endpoint": {
                    "$ref": "#/$defs/endpoint"
                },
                "cosmos_sdk_grpc_endpoint": {
                    "$ref": "#/$defs/grpc_endpoint"
                }
            },
            "additionalProperties": false
        }
    },
    "anyOf": [
        {
            "properties": {
                "is_initia_l1": { "const": true }
            }
        },
        {
            "properties": {
                "is_initia_l1": { "const": false }
            },
            "required": ["initia_l1_chain_id"]
        }
    ],
    "$defs": {
        "endpoint": {
            "type": "object",
            "required": [
                "address"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "format": "uri"
                },
                "provider": {
                    "type": "string"
                },
                "archive": {
                    "type": "boolean",
                    "default": false
                },
                "backoff_delay": {
                    "type": "integer",
                    "description": "Delay in milliseconds between request retires."
                },
                "basic_auth_required": {
                    "type": "boolean",
                    "default": false,
                    "description": "If basic HTTP authentication (username + password) is required to access this endpoint."
                },
                "index_for_skip": {
                    "type": "number",
                    "description": "The index for the basic auth salt generation."
                }
            }
        },
        "grpc_endpoint": {
            "allOf": [
                {
                    "$ref": "#/$defs/endpoint"
                },
                {
                    "type": "object",
                    "properties": {
                        "tls": {
                            "type": "boolean",
                            "description": "If TLS is required to access this GRPC endpoint.",
                            "default": false
                        }
                    }
                }
            ]
        }
    }
}

=== fragwuerdig/skip-go-registry/chains/inertiation-10/chain.json
{
  "$schema": "../../initia.chain.schema.json",
  "chain_id": "inertiation-10",
  "is_testnet": true,
  "chain_name": "inertia",
  "chain_type": "initia",
  "is_initia_l1": false,
  "initia_l1_chain_id": "initiation-2",
  "apis": {
    "tendermint_rpc_endpoint": {
      "address": "https://rpc.inertia.testnet.inrt.fi",
      "backoff_delay": 1000
    },
    "lcd_rest_endpoint": {
      "address": "https://rest.inertia.testnet.inrt.fi",
      "backoff_delay": 1000
    },
    "cosmos_sdk_grpc_endpoint": {
      "address": "grpc.inertia.testnet.inrt.fi:443",
      "backoff_delay": 0,
      "tls": true
    }
  }
}

=== fragwuerdig/skip-go-registry/chains/rehearsal-minimove-1/chain.json
{
  "$schema": "../../initia.chain.schema.json",
  "chain_id": "rehearsal-minimove-1",
  "is_testnet": true,
  "chain_name": "minimove",
  "chain_type": "initia",
  "is_initia_l1": false,
  "initia_l1_chain_id": "rehearsal-1",
  "apis": {
    "tendermint_rpc_endpoint": {
      "address": "https://rpc-rehearsal-minimove-1.anvil.asia-southeast.staging.initia.xyz",
      "provider": "Initia Labs",
      "backoff_delay": 1000
    },
    "lcd_rest_endpoint": {
      "address": "https://rest-rehearsal-minimove-1.anvil.asia-southeast.staging.initia.xyz",
      "provider": "Initia Labs",
      "backoff_delay": 1000
    },
    "cosmos_sdk_grpc_endpoint": {
      "address": "grpc-rehearsal-minimove-1.anvil.asia-southeast.staging.initia.xyz:443",
      "provider": "Initia Labs",
      "backoff_delay": 0,
      "tls": true
    }
  }
}

=== fragwuerdig/skip-go-registry/chains/miniwasm-2/chain.json
{
    "$schema": "../../initia.chain.schema.json",
    "chain_id": "miniwasm-2",
    "is_testnet": true,
    "chain_name": "miniwasm",
    "chain_type": "initia",
    "apis": {
        "tendermint_rpc_endpoint": {
            "address": "https://rpc-skip.miniwasm-2.initia.xyz",
            "provider": "Initia Labs",
            "backoff_delay": 1000,
            "basic_auth_required": true,
            "index_for_skip": 0
        },
        "lcd_rest_endpoint": {
            "address": "https://rest-skip.miniwasm-2.initia.xyz",
            "provider": "Initia Labs",
            "backoff_delay": 1000,
            "basic_auth_required": true,
            "index_for_skip": 0
        },
        "cosmos_sdk_grpc_endpoint": {
            "address": "grpc-skip.miniwasm-2.initia.xyz:443",
            "provider": "Initia Labs",
            "backoff_delay": 0,
            "tls": true,
            "basic_auth_required": true,
            "index_for_skip": 0
        }
    }
}

=== fragwuerdig/skip-go-registry/chains/landlord-2/chain.json
{
    "$schema": "../../initia.chain.schema.json",
    "chain_id": "landlord-2",
    "is_testnet": true,
    "chain_name": "civitia",
    "chain_type": "initia",
    "apis": {
        "tendermint_rpc_endpoint": {
            "address": "https://maze-rpc-sequencer-53ecf1d6-4fa1-4103-827f-a9430df97cef.ane1-prod-nocsm.newmetric.xyz",
            "backoff_delay": 1000
        },
        "lcd_rest_endpoint": {
            "address": "https://maze-rest-sequencer-53ecf1d6-4fa1-4103-827f-a9430df97cef.ane1-prod-nocsm.newmetric.xyz",
            "backoff_delay": 1000
        },
        "cosmos_sdk_grpc_endpoint": {
            "address": "maze-grpc-sequencer-53ecf1d6-4fa1-4103-827f-a9430df97cef.ane1-prod-nocsm.newmetric.xyz:443",
            "backoff_delay": 0,
            "tls": true
        }
    }
}

=== fragwuerdig/skip-go-registry/chains/rehearsal-minievm-1/chain.json
{
  "$schema": "../../initia.chain.schema.json",
  "chain_id": "rehearsal-minievm-1",
  "is_testnet": true,
  "chain_name": "minievm",
  "chain_type": "initia",
  "is_initia_l1": false,
  "initia_l1_chain_id": "rehearsal-1",
  "apis": {
    "tendermint_rpc_endpoint": {
      "address": "https://rpc-rehearsal-minievm-1.anvil.asia-southeast.staging.initia.xyz",
      "provider": "Initia Labs",
      "backoff_delay": 1000
    },
    "lcd_rest_endpoint": {
      "address": "https://rest-rehearsal-minievm-1.anvil.asia-southeast.staging.initia.xyz",
      "provider": "Initia Labs",
      "backoff_delay": 1000
    },
    "cosmos_sdk_grpc_endpoint": {
      "address": "grpc-rehearsal-minievm-1.anvil.asia-southeast.staging.initia.xyz:443",
      "provider": "Initia Labs",
      "backoff_delay": 0,
      "tls": true
    }
  }
}

=== fragwuerdig/skip-go-registry/chains/rave-1/chain.json
{
  "$schema": "../../initia.chain.schema.json",
  "chain_id": "rave-1",
  "is_testnet": false,
  "chain_name": "rave",
  "chain_type": "initia",
  "is_initia_l1": false,
  "initia_l1_chain_id": "interwoven-1",
  "apis": {
    "tendermint_rpc_endpoint": {
      "address": "https://rpc-rave-1.anvil.asia-southeast.initia.xyz",
      "backoff_delay": 1000
    },
    "lcd_rest_endpoint": {
      "address": "https://rest-rave-1.anvil.asia-southeast.initia.xyz",
      "backoff_delay": 1000
    },
    "cosmos_sdk_grpc_endpoint": {
      "address": "grpc-rave-1.anvil.asia-southeast.initia.xyz:443",
      "backoff_delay": 0,
      "tls": true
    }
  }
}

=== fragwuerdig/skip-go-registry/chains/embrmainnet-1/chain.json
{
  "$schema": "../../initia.chain.schema.json",
  "chain_id": "embrmainnet-1",
  "is_testnet": false,
  "chain_name": "embr",
  "chain_type": "initia",
  "is_initia_l1": false,
  "initia_l1_chain_id": "interwoven-1",
  "apis": {
    "tendermint_rpc_endpoint": {
      "address": "https://rpc-embrmainnet-1.anvil.asia-southeast.initia.xyz",
      "backoff_delay": 1000
    },
    "lcd_rest_endpoint": {
      "address": "https://rest-embrmainnet-1.anvil.asia-southeast.initia.xyz",
      "backoff_delay": 1000
    },
    "cosmos_sdk_grpc_endpoint": {
      "address": "grpc-embrmainnet-1.anvil.asia-southeast.initia.xyz:443",
      "backoff_delay": 0,
      "tls": true
    }
  }
}

=== fragwuerdig/skip-go-registry/chains/echelon-testnet-1/chain.json
{
  "$schema": "../../initia.chain.schema.json",
  "chain_id": "echelon-testnet-1",
  "is_testnet": true,
  "chain_name": "echelon",
  "chain_type": "initia",
  "is_initia_l1": false,
  "initia_l1_chain_id": "initiation-2",
  "apis": {
    "tendermint_rpc_endpoint": {
      "address": "https://rpc-echelon-testnet-1.anvil.asia-southeast.initia.xyz",
      "backoff_delay": 1000
    },
    "lcd_rest_endpoint": {
      "address": "https://rest-echelon-testnet-1.anvil.asia-southeast.initia.xyz",
      "backoff_delay": 1000
    },
    "cosmos_sdk_grpc_endpoint": {
      "address": "grpc.initia-test.rave.trade:443",
      "backoff_delay": 0,
      "tls": true
    }
  }
}
